# Configure incoming stream from Kafka
mp.messaging.incoming.order-events.connector=smallrye-kafka
mp.messaging.incoming.order-events.topic=orders
mp.messaging.incoming.order-events.value.deserializer=org.acme.OrderDeserializer
mp.messaging.incoming.order-events.auto.offset.reset=earliest

# Target local Kafka broker
kafka.bootstrap.servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

# Assign distinct port so it doesn't conflict with orders-service (8080)
quarkus.http.port=8081