name: Build and Test
permissions:
  contents: read
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      - name: Setup Java
        uses: actions/setup-java@dd06d9cba3e5552c54d9f8ea23572deb30010f7c
        with:
          distribution: temurin
          java-version: '21'
      - run: java --version
      - name: Test Orders App
        run: mvn test
        working-directory: orders
  build:
    name: Build Orders Service
    runs-on: ubuntu-24.04
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      - name: Setup Java
        uses: actions/setup-java@dd06d9cba3e5552c54d9f8ea23572deb30010f7c
        with:
          distribution: temurin
          java-version: '21'
      - run: java --version
      - name: Build Orders App
        run: mvn clean package -DskipTests
        working-directory: orders
      - name: Build Notifications App
        run: mvn clean package -DskipTests
        working-directory: notifications
  
      
